apiVersion: v2
name: homework
description: A Helm chart for Homework project
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: ingress-nginx
    version: 4.9.1
    repository: https://kubernetes.github.io/ingress-nginx