apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
data:
  nginx.conf: |
    http {

        server {
            listen 8000;
            server_name homework.otus;

            location / {
                root /homework;
                index index.html;
            }
            location /conf/dbuser {
                alias /conf/dbuser;
            }
            location /conf/dbpass {
                alias /conf/dbpass;
            }
            location /conf/dbconfig {
                alias /conf/dbconfig;
            }
        }
    }

    events {
        worker_connections  1024;
    }


