apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: networks-app
  namespace: argocd
spec:
  project: otus
  source:
    repoURL: https://github.com/Kuber-2025-04OTUS/vozmen_repo
    targetRevision: kubernetes-networks
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: homework
  syncPolicy:
    syncOptions:
      - CreateNamespace=true