apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: template-app
  namespace: argocd
spec:
  project: otus
  source:
    repoURL: https://github.com/Kuber-2025-04OTUS/vozmen_repo
    targetRevision: kubernetes-templating
    path: ./
    helm:
      parameters:
      - name: replicaCount
        value: "1"
  destination:
    server: https://kubernetes.default.svc
    namespace: homeworkhelm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true