apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homework-clusterRoleBinding
  namespace: homework
subjects:
- kind: ServiceAccount
  name: monitoring
  namespace: homework
roleRef:
  kind: ClusterRole
  name: homework-clusterrole
  apiGroup: rbac.authorization.k8s.io