apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.persistenceVolumeClaim.name }}
  namespace:  {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
spec:
  storageClassName: {{ .Values.app.persistenceVolumeClaim.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.app.persistenceVolumeClaim.resources.requests.storage }}