apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.app.storage.name }}
  annotations:
    "storageclass.kubernetes.io/is-default-class": {{ index .Values.app.storage.annotations "storageclass.kubernetes.io/is-default-class" | quote }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
provisioner: {{ .Values.app.storage.provisioner }}
reclaimPolicy: {{ .Values.app.storage.reclaimPolicy }}
volumeBindingMode: {{ .Values.app.storage.volumeBindingMode }}