deploymentMode: SingleBinary
loki:
  limits_config:
    volume_enabled: true
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames:
      chunks: "my-loki-logs"
      ruler: "my-loki-logs"
      admin: "my-loki-logs"
    type: s3
    s3:
      endpoint: "https://storage.yandexcloud.net"
      region: "ru-central1"
      secretAccessKey: "" # Удалил, так как git не принимает секреты
      accessKeyId: "" # Удалил, так как git не принимает секреты
  schemaConfig:
    configs:
    - from: "2025-01-01"
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: s3
      schema: v13
singleBinary:
  replicas: 1
  nodeSelector:
    node-role: infra
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
resultsCache:
  enabled: false
chunksCache:
  enabled: false
gateway:
  enabled: false
lokiCanary:
  enabled: false
test:
  enabled: false