apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.app.ClusterRoleBinding.name }}
subjects:
{{- range .Values.app.ClusterRoleBinding.subjects }}
- kind: {{ .kind }}
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }} # <-- ЭТО ПРАВИЛЬНО!
{{- end }}
roleRef:
  kind: {{ .Values.app.ClusterRoleBinding.roleRef.kind }}
  name: {{ .Values.app.ClusterRoleBinding.roleRef.name }}
  apiGroup: {{ .Values.app.ClusterRoleBinding.roleRef.apiGroup }}