apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.app.clusterRole.name }}
rules:
  - nonResourceURLs:
    {{- toYaml .Values.app.clusterRole.rules.nonResourceURLs | nindent 8 }}
    verbs:
    {{- toYaml .Values.app.clusterRole.rules.verbs | nindent 8 }}