apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.app.ClusterRoleBinding.name }}
  namespace: {{ .Release.Namespace }} 
subjects:
  {{- toYaml .Values.app.ClusterRoleBinding.subjects | nindent 0}}
roleRef:
  kind: {{ .Values.app.ClusterRoleBinding.roleRef.kind }}
  name: {{ .Values.app.ClusterRoleBinding.roleRef.name }}
  apiGroup: {{ .Values.app.ClusterRoleBinding.roleRef.apiGroup }}