apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: RoleBinding-admin
  namespace: homework
subjects:
  {{- toYaml .Values.app.RoleBinding_admin.subjects | nindent 0}}
roleRef:
  kind: {{ .Values.app.RoleBinding_admin.roleRef.kind }}
  name: {{ .Values.app.RoleBinding_admin.roleRef.name }}
  apiGroup: {{ .Values.app.RoleBinding_admin.roleRef.apiGroup }}