apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.secret_monitoring.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: monitoring
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
type: kubernetes.io/service-account-token