apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.secret_cd.name }}
  namespace: {{ .Release.Namespace }} 
  annotations:
    kubernetes.io/service-account.name: cd
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
type: kubernetes.io/service-account-token