apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.serviceAccount_monitoring.name }}
  namespace:  {{ .Release.Namespace }} 
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"