apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.serviceAccount_cd.name }}
  namespace:  {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"